### ISSUE TITLE
not accepting "domain.tld" as valid, needs "http://" or "https://" in front

### ISSUE THREAD

**Issue by malconfig** [inthecatsdreams/emoji-stealer#1]
when downloading using only "domain.tld", the script fails.
`user@machine:~/emoji_stealer$ python3 emoji_stealer.py domain.tld`
returns 

> Traceback (most recent call last):<br>
  File "emoji_stealer.py", line 58, in <module><br>
    main()<br>
  File "emoji_stealer.py", line 54, in main  
    api_data = read_api(api_url)  
  File "emoji_stealer.py", line 10, in read_api  
    req = Request(api_url, headers={"User-Agent": 'Mozilla/5.0'})  
  File "/usr/lib/python3.6/urllib/request.py", line 329, in __init__  
    self.full_url = url  
  File "/usr/lib/python3.6/urllib/request.py", line 355, in full_url  
    self._parse()  
  File "/usr/lib/python3.6/urllib/request.py", line 384, in _parse  
    raise ValueError("unknown url type: %r" % self.full_url)  
ValueError: unknown url type: 'domain.tld/api/v1/custom_emojis' 

adding http:// or https:// in front to the domain.tld fixes this.

*priority:* lower than low

**Comment by inthecatsdreams** [comment]
Hello,

I just pushed a fix for it, see: [https://github.com/inthecatsdreams/emoji-stealer/commit/4059bd76a61d3087f777e609df4b6b2d9cf5da49](fix)
